global:
  scrape_interval: 15s
  
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093" # Make sure this is the right name in Docker Compose

scrape_configs:
  - job_name: 'prometheus'
  # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
